"""
Jupyter Notebook builder.

Constructs a .ipynb file programmatically using nbformat,
embedding the actual analysis results and Gemini commentary.
"""
import nbformat as nbf
from typing import Any


def build(analysis: dict, commentary: dict | None = None) -> nbf.NotebookNode:
    """
    Build a complete Jupyter notebook from an analysis record.

    Args:
        analysis: Full Analysis dict from DB (converted via .to_dict())
        commentary: Optional result from gemini_client.code_commentary()

    Returns:
        nbformat NotebookNode ready to serialize with nbf.writes()
    """
    nb = nbf.v4.new_notebook()
    cells = []
    comments = {}
    if commentary and "cells" in commentary:
        comments = {c["step_index"]: c["markdown_comment"] for c in commentary["cells"]}

    filename = analysis.get("filename", "dataset.csv")
    problem_type = analysis.get("problem_type", "unknown")
    winning_model = analysis.get("winning_model", "N/A")
    target_col = analysis.get("target_col", "N/A")
    eda = analysis.get("eda_result") or {}
    results = analysis.get("results_json") or {}

    # ------------------------------------------------------------------
    # Cell 0: Title & EDA Narrative
    # ------------------------------------------------------------------
    narrative = eda.get("narrative", "Auto-generated analysis by ModelMind AI.")
    domain = analysis.get("domain") or eda.get("domain_guess", "Unknown")
    observations = eda.get("observations", [])
    obs_md = "\n".join(f"- {o}" for o in observations)

    cells.append(nbf.v4.new_markdown_cell(f"""# {filename} — ModelMind AI Analysis

**Problem Type:** {problem_type.title()}  
**Domain:** {domain}  
**Winning Model:** {winning_model}  
**Target Column:** {target_col}

---

## Dataset Summary

{narrative}

### Key Observations
{obs_md}

---
*Generated by [ModelMind AI](http://localhost:3000)*
"""))

    # ------------------------------------------------------------------
    # Cell 1: Imports
    # ------------------------------------------------------------------
    cells.append(_md_comment(comments.get(1, "### Step 1: Import Libraries\nAll required libraries for data loading, preprocessing, and modelling.")))
    cells.append(nbf.v4.new_code_cell("""import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score, f1_score, confusion_matrix,
    mean_squared_error, r2_score
)
import warnings
warnings.filterwarnings('ignore')

print("Libraries loaded ✓")
"""))

    # ------------------------------------------------------------------
    # Cell 2: Data Loading
    # ------------------------------------------------------------------
    cells.append(_md_comment(comments.get(2, "### Step 2: Load Data\nLoad the dataset and inspect its shape and first few rows.")))
    cells.append(nbf.v4.new_code_cell(f"""# Replace this path with your actual file location
df = pd.read_csv("{filename}")
print(f"Shape: {{df.shape}}")
df.head()
"""))

    # ------------------------------------------------------------------
    # Cell 3: EDA
    # ------------------------------------------------------------------
    shape = analysis.get("shape_rows", "?"), analysis.get("shape_cols", "?")
    cells.append(_md_comment(comments.get(3, f"### Step 3: Exploratory Data Analysis\nDataset has {shape[0]} rows × {shape[1]} columns.")))
    cells.append(nbf.v4.new_code_cell("""print("=== Basic Info ===")
print(df.dtypes)
print("\\n=== Missing Values ===")
print(df.isnull().sum())
print("\\n=== Descriptive Stats ===")
df.describe()
"""))

    # Correlation heatmap cell
    cells.append(nbf.v4.new_code_cell("""numeric_df = df.select_dtypes(include='number')
if len(numeric_df.columns) > 1:
    plt.figure(figsize=(12, 8))
    sns.heatmap(numeric_df.corr(), annot=True, fmt='.2f', cmap='coolwarm', center=0)
    plt.title('Correlation Heatmap')
    plt.tight_layout()
    plt.show()
"""))

    # ------------------------------------------------------------------
    # Cell 4: Preprocessing
    # ------------------------------------------------------------------
    cells.append(_md_comment(comments.get(4, "### Step 4: Preprocessing\nEncode categorical columns and prepare features and target.")))
    preprocess_code = f"""# Encode categorical columns
for col in df.select_dtypes(include=['object', 'category']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))

"""
    if target_col and target_col != "N/A":
        preprocess_code += f"""target_col = "{target_col}"
X = df.drop(columns=[target_col])
y = df[target_col]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Train: {{len(X_train)}} | Test: {{len(X_test)}}")
"""
    else:
        preprocess_code += """# Clustering — no target column
X = df.copy()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(f"Features shape: {X.shape}")
"""
    cells.append(nbf.v4.new_code_cell(preprocess_code))

    # ------------------------------------------------------------------
    # Cell 5: Model Training
    # ------------------------------------------------------------------
    cells.append(_md_comment(comments.get(5, f"### Step 5: Train Winning Model — {winning_model}\nThis was the best-performing model based on automated benchmarking.")))
    train_code = _generate_model_code(problem_type, winning_model, target_col)
    cells.append(nbf.v4.new_code_cell(train_code))

    # ------------------------------------------------------------------
    # Cell 6: Evaluation
    # ------------------------------------------------------------------
    cells.append(_md_comment(comments.get(6, "### Step 6: Evaluate Model Performance")))
    eval_code = _generate_eval_code(problem_type)
    cells.append(nbf.v4.new_code_cell(eval_code))

    # ------------------------------------------------------------------
    # Cell 7: Conclusion
    # ------------------------------------------------------------------
    explanation = {}
    if results:
        # Try to get explanation from results or cache
        explanation = results.get("explanation", {})
    summary = explanation.get("summary", "Analysis complete. See model metrics above.")
    actions = explanation.get("actions", [])
    actions_md = "\n".join(f"1. {a}" for a in actions) if actions else "- Review model metrics above."

    cells.append(nbf.v4.new_markdown_cell(f"""## Conclusion

{summary}

### Recommended Next Steps
{actions_md}

---
*This notebook was auto-generated by ModelMind AI and is ready to run in Jupyter or Google Colab.*
"""))

    nb.cells = cells
    nb.metadata = {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0",
        },
    }
    return nb


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _md_comment(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text)


def _generate_model_code(problem_type: str, winning_model: str, target_col: str | None) -> str:
    pt = problem_type.lower()

    if pt == "classification":
        model_map = {
            "Logistic Regression": "from sklearn.linear_model import LogisticRegression\nmodel = LogisticRegression(max_iter=500, random_state=42)",
            "Random Forest": "from sklearn.ensemble import RandomForestClassifier\nmodel = RandomForestClassifier(n_estimators=100, random_state=42)",
            "SVM": "from sklearn.svm import SVC\nmodel = SVC(probability=True, random_state=42)",
            "Gradient Boosting": "from sklearn.ensemble import GradientBoostingClassifier\nmodel = GradientBoostingClassifier(n_estimators=100, random_state=42)",
        }
        init_code = model_map.get(winning_model, "from sklearn.ensemble import RandomForestClassifier\nmodel = RandomForestClassifier(random_state=42)")
        return f"""{init_code}

pipe = Pipeline([('scaler', StandardScaler()), ('clf', model)])
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
print("Training complete ✓")
"""

    elif pt == "regression":
        model_map = {
            "Linear Regression": "from sklearn.linear_model import LinearRegression\nmodel = LinearRegression()",
            "Ridge": "from sklearn.linear_model import Ridge\nmodel = Ridge(alpha=1.0)",
            "Lasso": "from sklearn.linear_model import Lasso\nmodel = Lasso(alpha=0.1, max_iter=2000)",
            "XGBoost": "import xgboost as xgb\nmodel = xgb.XGBRegressor(n_estimators=100, random_state=42, verbosity=0)",
        }
        init_code = model_map.get(winning_model, "from sklearn.linear_model import LinearRegression\nmodel = LinearRegression()")
        return f"""{init_code}

pipe = Pipeline([('scaler', StandardScaler()), ('reg', model)])
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
print("Training complete ✓")
"""

    elif pt == "clustering":
        return """from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Using k determined by automated elbow method
model = KMeans(n_clusters=3, random_state=42, n_init='auto')
labels = model.fit_predict(X_scaled)
df['Cluster'] = labels
print(f"Cluster distribution:\\n{df['Cluster'].value_counts()}")
"""

    else:
        return """from statsmodels.tsa.statespace.sarimax import SARIMAX

# Ensure your index is a DatetimeIndex
train_len = int(len(df) * 0.8)
train, test = df.iloc[:train_len], df.iloc[train_len:]

model = SARIMAX(train, order=(1, 1, 1)).fit(disp=False)
predictions = model.forecast(steps=len(test))
print("Forecast complete ✓")
"""


def _generate_eval_code(problem_type: str) -> str:
    pt = problem_type.lower()

    if pt == "classification":
        return """print(f"Accuracy:  {accuracy_score(y_test, y_pred):.4f}")
print(f"F1 Score:  {f1_score(y_test, y_pred, average='weighted'):.4f}")

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.show()
"""
    elif pt == "regression":
        return """from sklearn.metrics import mean_absolute_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"RMSE: {rmse:.4f}")
print(f"MAE:  {mean_absolute_error(y_test, y_pred):.4f}")
print(f"R²:   {r2_score(y_test, y_pred):.4f}")

plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.5, edgecolors='k', linewidth=0.5)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title('Actual vs Predicted')
plt.tight_layout()
plt.show()
"""
    elif pt == "clustering":
        return """from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

sil = silhouette_score(X_scaled, labels)
print(f"Silhouette Score: {sil:.4f}")

pca = PCA(n_components=2, random_state=42)
coords = pca.fit_transform(X_scaled)
plt.figure(figsize=(8, 6))
scatter = plt.scatter(coords[:, 0], coords[:, 1], c=labels, cmap='tab10', alpha=0.7)
plt.colorbar(scatter, label='Cluster')
plt.title('Cluster Visualization (PCA 2D)')
plt.tight_layout()
plt.show()
"""
    else:
        return """from sklearn.metrics import mean_squared_error, mean_absolute_error
rmse = np.sqrt(mean_squared_error(test, predictions))
print(f"RMSE: {rmse:.4f}")
print(f"MAE:  {mean_absolute_error(test, predictions):.4f}")

plt.figure(figsize=(12, 5))
plt.plot(train.index, train.values, label='Train', color='blue')
plt.plot(test.index, test.values, label='Actual', color='green')
plt.plot(test.index, predictions.values, label='Forecast', color='red', linestyle='--')
plt.legend()
plt.title('Time Series Forecast')
plt.tight_layout()
plt.show()
"""
